stock_codes:
  - code: "000333"
    name: 美的集团
  - code: "000651"
    name: 格力电器
  - code: "002304"
    name: 洋河股份
  - code: "002959"
    name: 小熊电器
  - code: "000858"
    name: 五粮液
  - code: "600436"
    name: 片仔癀
  - code: "603345"
    name: 安井食品
  - code: "600415"
    name: 小商品城
  - code: "605499"
    name: 东鹏饮料
  - code: "600750"
    name: 江中药业
