name: daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  execute-python-script:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.3.1
        poetry config virtualenvs.in-project true
        poetry install

    - name: Execute Python Script
      run: python scripts/md_make.py  
      
    - name: Commit and Push Changes
      run: |
        git config --global user.name 'haifeng'
        git config --global user.email '1353120323@qq.com'
        git pull
        git add .
        git commit -m "Auto-update files"
        git push origin 

