name: 执行hexo部署

on:
  workflow_dispatch:

jobs:
  execute-python-script:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1

    - name: Cache NPM dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install Hexo CLI
      run: npm install -g hexo-cli

    - name: Install dependencies
      run: npm install

    - name: Generate static pages
      run: hexo generate

    - name: Commit and Push changes
      run: |
        git config --global user.name 'action'
        git config --global user.email 'action@example.com'
        git add .
        git commit -m "Auto-update files"
        git push origin HEAD:${{ github.ref_name }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
    - name: Hexo Action
      # You may pin to the exact commit or the version.
      # uses: sma11black/hexo-action@08f5143fa402cdaccf9fc016d6bc91329f082eb0
      uses: sma11black/hexo-action@v1.0.4
      with:
        # Github user name
        user_name: "test"
        # Github email
        user_email: "test@example.com"
        # The deploy key for Github Pages repo
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        # Git commit messages to your GitHub Pages repository.
        commit_msg: ${{ github.event.head_commit.message }} 
              
