name: 生成markdown

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  execute-python-script:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.3.1
        poetry config virtualenvs.in-project true
        poetry install

    - name: Execute Python script
      run: python scripts/md_make.py  # 替换成你的脚本文件名

    - name: Commit and Push changes
      run: |
        git config --global user.name 'haifeng'
        git config --global user.email '1353120323@qq.com'
        git pull
        git add .
        git commit -m "Auto-update files"
        git push origin 

    - name: Copy file to another repository
      run: |
        cd ..
        git clone https://github.com/dychf/dychf.github.io.git
        cp -r ./automation/md/* ./dychf.github.io/docs/
        cd dychf.github.io
        git config --global user.name 'haifeng'
        git config --global user.email '1353120323@qq.com'
        git pull
        git add .
        git commit -m "Add file from automation"
        git push --force --quiet "https://${{ secrets.PAGE }}@$GITHUB_REPO" master:master
      env:
        GITHUB_REPO: github.com/dychf/dychf.github.io
