name: 自动生成markdown文件测试

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  execute-python-script:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # 选择你需要的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 如果你有依赖项，请在此处或在 separate requirements.txt 文件中安装
        # pip install -r requirements-punch.txt

    - name: Execute Python script
      run: python scripts/md_make.py  # 替换成你的脚本文件名

    - name: Commit and Push changes
      run: |
        git config --global user.name 'action'
        git config --global user.email 'action@example.com'
        git add .
        git commit -m "Auto-update files"
        git push origin HEAD:${{ github.ref_name }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Copy file to another repository
      run: |
        cd ..
        git clone https://github.com/dychf/dychf.github.io.git
        cp ./automation/md/* ./dychf.github.io/source/_posts/
        cd dychf.github.io
        git config user.name 'your-username'
        git config user.email 'your-email@example.com'
        git add .
        git commit -m "Add file"
        git push https://github.com/dychf/dychf.github.io.git master 
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
