name: 自动打卡

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7-11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Shanghai"
      RUN_ENV: "production" # within ['production', 'development']
      POWER: 16
    steps:
      # ============================================
      # TODO [√] 检查工作分支及 Workflows 运行环境
      # ============================================
      - name: Checkout
        uses: actions/checkout@v2
      # ============================================
      # TODO [√] 创建 Python3.6+ 编译环境
      # ============================================
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # ============================================
      # TODO [√] 安装 Project 第三方依赖
      # ============================================
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-punch.txt ]; then pip install -r requirements-punch.txt; fi
      # ============================================
      # TODO [√] 测试 Scaffold 脚手架指令
      # ============================================
      - name: Run punch
        run: |
          python scripts/punch.py run --env=${{ env.RUN_ENV }} --power=${{ env.POWER }}
      
